[audio]
enable_overdrive = true

[bar]
order = [ "topbar", "workspaces" ]

    [bar.topbar]
    auto_hide = true
    background_opacity = 0.80000000000000004
    border_width = 1.0
    center = [ "weather", "clock", "date" ]
    end = [ "tray", "caffeine", "laptopScreenToggle", "network", "bluetooth", "volume", "battery", "session" ]
    layer = "overlay"
    margin_ends = 10
    reserve_space = false
    scale = 1.2
    start = [ "cpu", "temp", "ram", "sysmon" ]

    [bar.workspaces]
    background_opacity = 0.0
    capsule = true
    capsule_opacity = 0.75
    center = [ "workspaces" ]
    enabled = true
    end = []
    layer = "overlay"
    position = "bottom"
    reserve_space = false
    start = []

[calendar]
enabled = true

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

[location]
auto_locate = true

[lockscreen]
blurred_desktop = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-widget-0000000000000001",
    "lockscreen-login-box@DP-6",
    "lockscreen-login-box@DP-4",
    "lockscreen-login-box@eDP-1"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
    box_height = 0.0
    box_width = 0.0
    cx = 1024.0
    cy = 1029.0
    output = "DP-4"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@DP-6"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 1077.0
    output = "DP-6"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 1077.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 112.0
    box_width = 240.0
    cx = 960.0
    cy = 456.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        clock_style = "digital"
        color = "primary"
        format = "{:%H:%M:%S}"

[nightlight]
enabled = true
force = true
temperature_day = 6000
temperature_night = 5000

[notification]
layer = "overlay"

[osd]
offset_y = 50
position = "bottom_center"
scale = 1.25

[plugins]
enabled = []

    [[plugins.source]]
    kind = "path"
    location = "/home/victor/.config/noctalia/plugins/"
    name = "legacy-v4"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "my-repo"

[shell]
password_style = "random"
screen_time_enabled = true
settings_show_advanced = true
telemetry_enabled = true

    [shell.screenshot]
    filename_pattern = "%Y%m%d_%H%M%S"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    shortcut = "KP_2"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "KP_3"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "KP_4"
    variant = "destructive"

[system.monitor]
cpu_temp_activity_threshold = 61
ram_pct_activity_threshold = 70

[theme]
source = "wallpaper"

[wallpaper]
directory = "/home/victor/.config/hypr/wallpapers"

    [wallpaper.default]
    path = "/home/victor/.config/hypr/wallpapers/wallpaper.jpg"

    [wallpaper.last]
    path = "/home/victor/.config/hypr/wallpapers/wallpaper.jpg"

[widget.battery]
display_mode = "graphic"

[widget.cat]
audio_spectrum = true
rave_mode = true
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clock]
format = "{:%H:%M:%S}"

[widget.laptopScreenToggle]
command = "/home/victor/.config/hypr/scripts/laptopLidClose.sh"
glyph = "device-laptop"
type = "custom_button"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false

[widget.ram]
stat = "ram_pct"

[widget.sysmon]
stat = "disk_pct"

[widget.weather]
show_condition = false