[mgr]
prepend_keymap = [
    # Compress, extract
    { on = [ "c", "a", "a" ], run = "plugin compress", desc = "Compress" },
    { on = [ "c", "a", "p" ], run = "plugin compress -p", desc = "Compress (password)" },
    { on = [ "c", "a", "h" ], run = "plugin compress -ph", desc = "Compress (password+header)" },
    { on = [ "c", "a", "l" ], run = "plugin compress -l", desc = "Compress (compression level)" },
    { on = [ "c", "a", "u" ], run = "plugin compress -phl", desc = "Compress (password+header+level)" },
    { on = [ "e" ], run = 'shell -- ~/.local/bin/compress.sh -x "$1" .', desc = "Extract archive" },


    # Open terminal
    { on = [ "T" ], run = "shell --orphan --confirm kitty", desc = "Open terminal at current dir" },


    # Undo delete
    { on = [ "u" ], run = "plugin restore", desc = "Restore last deleted files/folders" },
    { on = [ "U" ], run = "plugin restore -- --interactive --interactive-overwrite", desc = "Restore deleted files/folders (Interactive overwrite)" },


    # Go to specific directories
    { on = [ "g", "t" ], run = "cd ~/.local/share/Trash/files", desc = "Go to Trash" },
    { on = [ "g", "m" ], run = "cd /mnt", desc = "Go to /mnt" },
    { on = [ "g", "e" ], run = "cd ~/Desktop", desc = "Go to Desktop" },
    { on = [ "g", "p" ], run = "cd ~/Pictures", desc = "Go to Pictures" },


    # Move faster
    { on = "K", run = "arrow -50%", desc = "Move cursor up half page" },
    { on = "J", run = "arrow 50%",  desc = "Move cursor down half page" },

    # Mount
    # { on = [ "M", "m" ], run = "plugin gvfs -- select-then-mount", desc = "Select device then mount" },
    # or this if you want to jump to mountpoint after mounted
    { on = [ "M", "m" ], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device to mount and jump to its mount point" },

    # { on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount", desc = "Select device then unmount" },
    # Or this if you want to unmount and eject device.
    #   -> Ejected device can safely be removed.
    #   -> Ejecting a device will unmount all paritions/volumes under it.
    #   -> Fallback to normal unmount if not supported by device.
    { on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },

    # Also support force unmount/eject.
    #   -> Ignore outstanding file operations when unmounting or ejecting
    { on = [ "M", "U" ], run = "plugin gvfs -- select-then-unmount --eject --force", desc = "Select device then force to eject/unmount" },

    # Jump
    { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device", desc = "Select device then jump to its mount point" },
]


