_G.mainMod = "SUPER"
_G.terminal = "kitty"
_G.fileManager = "kitty -e yazi"
_G.menu = "walker"

hl.config({
    general = {
        -- autogenerated = 0
    }
})

hl.env("XCURSOR_THEME", "Vimix-cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("EDITOR", "nvim")

hl.on("hyprland.start", function()
    hl.exec_cmd("export GSK_RENDERER=ngl")
    hl.exec_cmd("xdg-settings set default-web-browser firefox.desktop")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
