_G.mainMod = "SUPER"
_G.terminal = "kitty"
_G.fileManager = "kitty -e yazi"
_G.menu = "walker"

hl.config({
    general = {
        -- autogenerated = 0
    }
})

hl.env("XCURSOR_THEME", "Vimix-cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("EDITOR", "nvim")
hl.env("GSK_RENDERER", "ngl")
