hl.on("hyprland.start", function()
    -- hl.exec_cmd("hyprsunset -t 5000")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/bin/hyprland-monitor-attached ~/.config/hypr/scripts/get_bing_image.sh")
    hl.exec_cmd("systemctl --user restart wireplumber.service")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("blueman-applet")
    -- hl.exec_cmd("hypridle")
    hl.exec_cmd("elephant")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("sway-audio-idle-inhibit")
    -- hl.exec_cmd("telegram-desktop")
    hl.exec_cmd(_G.terminal or "kitty")
    -- hl.exec_cmd("sudo tzupdate")
    hl.exec_cmd("noctalia")
end)

hl.exec_cmd("hyprswitch init --show-title --custom-css $HOME/.config/hypr/style/hyprswitch.css &")
