hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    -- hl.exec_cmd("~/.config/hypr/scripts/get_bing_image.sh")
    hl.exec_cmd("noctalia")
    -- hl.exec_cmd("systemctl --user restart wireplumber.service")
    -- hl.exec_cmd("systemctl --user start hyprpolkitagent")
    -- hl.exec_cmd("blueman-applet")
    hl.exec_cmd("elephant")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("sway-audio-idle-inhibit")
    -- hl.exec_cmd("telegram-desktop")
    hl.exec_cmd(_G.terminal or "kitty")
    -- hl.exec_cmd("sudo tzupdate")
end)

